### PR TITLE
melobot v3 tests for lower levels

### PR DESCRIPTION
**Pull request by ChlorideP**
Basically some tests on melobot framework, including the following levels:

- [x] Basic utilities
- [ ] io source (mainly abstract in `melobot.io`)
- [ ] adaptor
- [ ] handler

> [!note]
> The check box ahead shall be considered as progress, which is really slow right now though.

> This project is definitely a lesson of `async` for me, since I NEVER tried those async tricks.
> I just kept using threading stuffs (or sometimes multi-processing) to try to fasten my runtime efficiency.
>
> ~~I would always be grateful to have the chance communicating with dalao like u,~~
> ~~since we met in the group of Dr.Black XD~~

### CODE REVIEW

**Comment by ChlorideP** [comment]
枕么还传了个 merge commit …… 到时候可能还需要 rebase，，

**Comment by aicorein** [comment]
> 枕么还传了个 merge commit …… 到时候可能还需要 rebase，，

没事，最后写完统一压缩就行。

**Comment by aicorein** [comment]
> > 枕么还传了个 merge commit …… 到时候可能还需要 rebase，，
> 
> 没事，最后写完统一压缩就行。

当然你也可以不压缩，这边合并之后会自动压缩。

**Comment by ChlorideP** [comment]
传奇鸽王 ChlorideP 又整烂活辣（

**Comment by aicorein** [comment]
> ~传奇鸽王 ChlorideP 又整烂活辣（~
> 
> ~然后不出所料又炸测试了。~
> 
> 姑且可以往下写了。

加油

**Comment by aicorein** [comment]
`melobot.utils` 部分的测试我抽空全部补好了。先合并这部分吧，剩下的测试干脆分成多个 PR。
感谢氯喵的付出哦，辛苦啦❤️

**Review by aicorein — APPROVED** [review]

**Comment by ChlorideP** [comment]
> `melobot.utils` 部分的测试我抽空全部补好了。先合并这部分吧，剩下的测试干脆分成多个 PR。 感谢氯喵的付出哦，辛苦啦❤️

（蹭）

**Pull request merged**
